[package]
name = "tari-lp-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
crossterm = "0.26.1"
tact = { path = "../core/tact" }
thiserror = "1.0.40"
tui = "0.19.0"
