[package]
name = "tact"
description = "The tiny actors library"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
